<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWpf>true</UseWpf>
    <RootNamespace>DuplicateFileFinder</RootNamespace>
    <AssemblyName>DuplicateFileFinder</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <StartupObject>DuplicateFileFinder.App</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes" Version="4.9.0" />
    <PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="DuplicateFileFinder.Tests\**" />
    <EmbeddedResource Remove="DuplicateFileFinder.Tests\**" />
    <None Remove="DuplicateFileFinder.Tests\**" />
    <Page Remove="DuplicateFileFinder.Tests\**" />
  </ItemGroup>

</Project>
